paths:
  input_genomic_file: '/path/to/genomic_viral_arg.fasta'
  input_protein_file: '/path/to/protein_viral_arg.fasta'
  output_genomad_dir: '/path/to//genomad'
  genomad_db: '/path/to/database/genomad/genomad_db/'
  output_isescan_dir: '/path/to/isescan'
  output_integron_dir: '/path/to/integron'
  diamond_mobileOG_db: '/path/to/database/mobileOG-db/mobileOG-db_beatrix-1.6.dmnd'
  output_mobileOG_dir: '/path/to/mobileOG'
  genomad_env: '/path/to/envs/genomad_env.yaml'
  isescan_env: '/path/to/envs/isescan_env.yaml'
  integron_env: '/path/to/integron_env.yaml'
  mobileog_env: '/path/to/envs/mobileog_env.yaml'
